apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adservice
  namespace: argocd
  labels:
    name: adservice
spec:
  syncPolicy:
    automated: {}
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/retail-store-saas/adservice.git
    targetRevision: HEAD
    path: kubernetes-manifests
    kustomize:
      images:
        - 112776155351.dkr.ecr.eu-west-1.amazonaws.com/adservice:3b2ceb32509930565ee34bd88b006fe1f1bebb2a
