apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: currencyservice
  namespace: argocd
  labels:
    name: currencyservice
spec:
  syncPolicy:
    automated: {}
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/retail-store-saas/currencyservice.git
    targetRevision: HEAD
    path: kubernetes-manifests
    kustomize:
      images:
        - 112776155351.dkr.ecr.eu-west-1.amazonaws.com/currencyservice:c7e9a64dc417ac91d81ee0464f54c09236f55440
