apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  labels:
    name: frontend
spec:
  syncPolicy:
    automated: {}
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/retail-store-saas/frontend.git
    targetRevision: HEAD
    path: kubernetes-manifests
    kustomize:
      images:
        - 112776155351.dkr.ecr.eu-west-1.amazonaws.com/frontend:f1100e74a443340722dc5991194d7d05656cfd86
