apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paymentservice
  namespace: argocd
  labels:
    name: paymentservice
spec:
  syncPolicy:
    automated: {}
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/retail-store-saas/paymentservice.git
    targetRevision: HEAD
    path: kubernetes-manifests
    kustomize:
      images:
        - 112776155351.dkr.ecr.eu-west-1.amazonaws.com/paymentservice:271921f02c7dc352d301aa3531f473a7ae613126
