apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: productcatalogservice
  namespace: argocd
  labels:
    name: productcatalogservice
spec:
  syncPolicy:
    automated: {}
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/retail-store-saas/productcatalogservice.git
    targetRevision: HEAD
    path: kubernetes-manifests
    kustomize:
      images:
        - 112776155351.dkr.ecr.eu-west-1.amazonaws.com/productcatalogservice:7bec786dada3f594aa25f74184af0e5b157a6ed9
